name: LocalStack Terraform Test

on:
  push:
    branches:
      - "**"

  workflow_dispatch: {}

jobs:
  localstack-terraform-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build and Start LocalStack Container
        run: |
          docker compose up -d

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Run Terraform Init, Validation and Plan
        run: |
          terraform init
          terraform validate
          terraform fmt --recursive --check
          terraform plan
          terraform show

      - name: Run Terraform Test
        run: |
          terraform test

      - name: Stop and Delete LocalStack Container
        if: always()
        run: docker compose down
